name: Update README Daily

on:
  schedule:
    - cron: '0 19 * * *'  

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update readme.md
        run: |
          export TZ=Asia/Kolkata
          YESTERDAY=$(date -d "yesterday" +%-d)
          DATE=$(date -d "yesterday" +'%Y-%m-%d')

          IMAGE_URL="Progress/2025/Day${YESTERDAY}.jpg"
          
          # Replace image URL
          sed -i "s|!\[Day Image\](.*)|![Day Image]($IMAGE_URL)|" readme.md

          # Update or append Last updated date
          if grep -q "Last updated:" readme.md; then
            sed -i "s|Last updated: .*|Last updated: $DATE|" readme.md
          else
            echo "Last updated: $DATE" >> readme.md
          fi

      - name: Commit changes
        run: |
          git config --local user.email "lavintom007@gmail.com"
          git config --local user.name "Lavin-Tom"
          git add readme.md
          git commit -m "Update image link and last updated date for $DATE" || echo "No changes to commit"
          git push
