name: Update README Daily

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:  

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  
        
      - name: Update readme.md
        run: |
          # Get yesterday's day and date
          YESTERDAY=$(date -d "yesterday" +'%d')
          DATE=$(date -d "yesterday" +'%Y-%m-%d')
          
          # Define the image URL based on yesterday's day
          IMAGE_URL="Progress/Day${YESTERDAY}.jpg"
          
          # Update the README with the new image link and date
          sed -i "s|!\[Day Image\](.*)|![Day Image]($IMAGE_URL)|" readme.md
          sed -i "s|Today's date: .*|Today's date: $DATE|" readme.md || echo "Today's date: $DATE" >> readme.md

      - name: Commit changes
        run: |
          git config --local user.email "lavintom007@gmail.com"
          git config --local user.name "Lavin-Tom"
          git commit -am "Update image link for $(date -d "yesterday" +'%Y-%m-%d')" || echo "No changes to commit"
          git push
